### ISSUE TITLE
Nice Job!!

### ISSUE THREAD

**Issue by EliotChen8** [LiferLifer/EE351-Lab-Reports#1]
我可以把我的也弄上来么？

- 有两次报告的markdown和相应的图片之类的；
- 期中之前搞了个大思维导图，感觉内容虽然不完全全但是对考试有帮助，想把`.xmind`放上来和后续同学们一起完善。

说不定可以把这个库搞成一个微机专用~~集中~~求生营

**Comment by LiferLifer** [comment]
已添加合作者。
